apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server               # ← must be non-empty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
        - name: static-server
          image: auma1997/static-server:1.0
          ports:
            - containerPort: 8080