apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
      - name: static-server
        image: aum1997/static-server:1.0
        ports:
        - containerPort: 8080