apiVersion: v1
kind: Service
metadata:
  name: static-server-service      # ← must be non-empty
spec:
  selector:
    app: static-server
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer